import { useRouter } from 'next/router';
import Head from 'next/head';
import Layout from '../componets/layout';
import { useReadContract, useWaitForTransactionReceipt, useWriteContract, useAccount } from 'wagmi';
import swapAbi from '../core/swap_abi.json';
import erc20Abi from '../core/erc20_abi.json';

const Home: NextPage = () => {
  const router = useRouter();

  const handlePointsSystemClick = () => {
    router.push('/pointsSystem');
  };

  const handleRestaurantClick = (restaurant: string) => {
    router.push(`/restaurant/${restaurant}`);
  };
  const { address, isConnected } = useAccount()
  const { data: hash, isPending, writeContract } = useWriteContract()
  const { isLoading: isConfirming, isSuccess: isConfirmed } =
    useWaitForTransactionReceipt({
      hash,
    })

  const targetAmount = 100000;

  const _swapAmount = useReadContract({
    abi: swapAbi,
    address: '0x09f8cefc8afD01aFF85e0bcb7C426ed2692116B3',
    functionName: 'getAmountIn',
    args: [targetAmount]
  })
  console.log("swapAmount", _swapAmount.data);

  const msleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
  const handleClick = async () => {
    if (!address) {
      console.log("address not ");
      return;

    } 
    console.log("address", address);
    writeContract({
      address: '0x09f8cefc8afD01aFF85e0bcb7C426ed2692116B3',
      abi: swapAbi,
      functionName: 'swap',
      args: [
        '0x750ebea257a20F10217D46c914eea89094aa86d0',
        BigInt(_swapAmount.data as any),
      ],
    })
    for (;isConfirmed;) {
      console.log("Pending...");
      await msleep(1000);
    }
    alert(hash);
  }

  const handleApprove = async () => {
    writeContract({
      address: '0x657296a72483F8F330287B2F1E20293a2a2C2F52',
      abi: erc20Abi,
      functionName: 'approve',
      args: [
        address,
        _swapAmount.data,
      ],
      account: address,
    })
  }

  return (
    <Layout>
      <Head>
        <title>TeleDine</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <button className="points-system" onClick={handlePointsSystemClick}>
          My $TLD coins
        </button>
        <h2>Choose The Restaurant!</h2>
        <div className="restaurant-grid">
          <button className="restaurant-button" onClick={() => handleRestaurantClick('A')}>餐廳 A</button>
          <button className="restaurant-button" onClick={() => handleRestaurantClick('B')}>餐廳 B</button>
          <button className="restaurant-button" onClick={() => handleRestaurantClick('C')}>餐廳 C</button>
          <button className="restaurant-button" onClick={() => handleRestaurantClick('D')}>餐廳 D</button>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
