import { useRouter } from 'next/router';
import Head from 'next/head';
import Layout from '../componets/layout';

const Home: NextPage = () => {
  const router = useRouter();

  const handlePointsSystemClick = () => {
    router.push('/pointsSystem');
  };

  const handleRestaurantClick = (restaurant: string) => {
    router.push(`/restaurant/${restaurant}`);
  };
  
  return (
    <Layout>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      {/* <div>
        <div className="container header-content">
          <div className="logo-container">
            <a href="#/" className="logo-link">
              <Image src={logo_icon} alt="TeleDine Logo" className="logo-image" width={50} height={50} />
            </a>
            <h1>TeleDine</h1>
          </div>
          <ConnectButton />
        </div>
      </div> */}
      <main>
        <button className="points-system" onClick={handlePointsSystemClick}>
          My $TLD coins
        </button>
        <h2>Choose The Restaurant!</h2>
        <div className="restaurant-grid">
          <button className="restaurant-button" onClick={() => handleRestaurantClick('A')}>餐廳 A</button>
          <button className="restaurant-button" onClick={() => handleRestaurantClick('B')}>餐廳 B</button>
          <button className="restaurant-button" onClick={() => handleRestaurantClick('C')}>餐廳 C</button>
          <button className="restaurant-button" onClick={() => handleRestaurantClick('D')}>餐廳 D</button>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
